### ISSUE TITLE
About PSD matrix

### ISSUE THREAD

**Issue by shanhaidexiamo** [funcwj/aps#50]
https://github.com/funcwj/aps/blob/3f46e4750923a3c50529403614eda11118b53b9a/aps/asr/filter/mvdr.py#L57
您好，我想问一下，这行代码是MVDR的分子部分，应该是mask之后的特征和其共轭转置矩阵乘，您的写法后面使用的是mask之前的特征，不会有问题嘛？

**Comment by funcwj** [comment]
一般情况下用 mask * x * x^H就行了，你的意思是要写成(mask * x) * (mask * x)^H 对吧

**Comment by shanhaidexiamo** [comment]
是的，不知道两者差距是很大么，我看您基本都是这样写的

**Comment by funcwj** [comment]
差别会有，可能不会很大，我之前的recipe代码也是这么做的，follow的是Heymann的文章，你可以看一下这里[https://github.com/funcwj/setk/tree/master/doc/adaptive_beamformer](https://github.com/funcwj/setk/tree/master/doc/adaptive_beamformer)的文献1

**Comment by shanhaidexiamo** [comment]
好的，非常感谢！
